[package]
name = "aero_gfx"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
bit_field = "0.10.1"

[dependencies.font8x8]
version = "0.3"
default-features = false
features = ["unicode"]
