[package]
name = "aero_shell"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
aero_syscall = { path = "../../src/aero_syscall" }
