[package]
name = "aero_hal"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if = "1.0.0"
bit_field = "0.10.1"
bitflags = "1.2"
