[package]
name = "std"
version = "0.1.0"
authors = ["czapek1337 <czapek1337@gmail.com>"]
edition = "2021"

[dependencies]
aero_rt = { path = "../aero_rt" }
aero_syscall = { path = "../aero_syscall" }
