[package]
name = "aero_build"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2021"

[dependencies]
structopt = "0.3.22"
fs_extra = "1.2.0"
xshell = "0.1.14"
json = "0.12.4"
anyhow = "1.0.42"
