[package]
name = "aero_boot"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.14", default-features = false }
uefi = "0.8.0"
xmas-elf = "0.7.0"
rlibc = "1"
uefi-services = "0.5.0"
