[package]
name = "aero_boot"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
reqwest = "0.11.3"
structopt = "0.3.21"
tokio = { version = "1.5.0", features = ["macros", "rt", "rt-multi-thread"] }
