[workspace]
members = [
    "aero_kernel",
    "aero_boot",

    "aero_gfx",
    "aero_hal",
    "aero_syscall"
]

[profile.dev]
opt-level = 3
lto = true
debug = true

[profile.release]
lto = true
debug = true
