[unstable]
patch-in-config = true

[build]
rustc = "@BUILD_ROOT@/tools/host-rust/bin/rustc"
target = "x86_64-unknown-aero-system"

[target.x86_64-unknown-aero-system]
linker = "@BUILD_ROOT@/tools/system-gcc/bin/x86_64-aero-gcc"

[patch.crates-io]
libc = { path = "@SOURCE_ROOT@/bundled/rust-libc" }
