[package]
name = "aero_kernel"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[features]
round-robin = []

default = ["round-robin"]

[dependencies]
spin = "0.9.2"
bitflags = "1.2.1"
bit_field = "0.10.1"
log = "0.4.14"
raw-cpuid = "10.0.0"
xmas-elf = "0.8.0"
paste = "1.0.5"
cfg-if = "1.0.0"
hashbrown = "0.11.2"
rustc-demangle = "0.1.20"
lru = "0.6.5"
stivale-boot = "0.2.3"
intrusive-collections = "0.9.2"
aml = { path = "../../../acpi/aml" }

[dependencies.font8x8]
version = "0.3.1"
default-features = false
features = ["unicode"]

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies.linked_list_allocator]
version = "0.9.0"
default-features = false
features = ["const_mut_refs"]

[dependencies.aero_syscall]
path = "../aero_syscall/"

[build-dependencies]
nasm-rs = { version = "0.2", features = ["parallel"] }
