[package]
name = "aero_kernel"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
spin = "0.9"
bitflags = "1.2"
x86_64 = "0.14.1"
bit_field = "0.10.1"
linked_list_allocator = "0.9.0"
log = "0.4"
raw-cpuid = "9.0"
xmas-elf = "0.7"
paste = "1.0"
cfg-if = "1.0.0"
hashbrown = "0.11.2"

[dependencies.font8x8]
version = "0.3"
default-features = false
features = ["unicode"]

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

#####################################

[dependencies.aero_syscall]
path = "../aero_syscall/"

[dependencies.aero_gfx]
path = "../aero_gfx/"

[dependencies.aero_boot]
path = "../aero_boot/"

#####################################

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
nasm-rs = { version = "0.2", features = ["parallel"] }
aero_build = { path = "../../aero_build/" }
