name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly

    - name: Install `rust-src` Rustup Component
      run: rustup component add rust-src llvm-tools-preview
    - name: Install bootimage
      run: cargo install bootimage
    - name: Run build
      run: cargo build
    - name: Build Docs
      run: cargo doc
    - name: Deploy Docs
      run: cd target/x86_64-aero_os/doc/aero/
    - run: git init
    - run: git config --global user.email andypythonappdeveloper@gmail.com
    - run: git config --global user.name Andy-Python-Programmer
    - run: git remote add origin https://${{secrets.AERO_DOCS}}@github.com/Andy-Python-Programmer/aero.git
    - run: git checkout -b gh-pages
    - run: git add --all
    - run: git commit -m "Nightly - Aero Docs"
    - run: git push origin gh-pages -f