name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install nasm
      run: sudo apt-get install -y nasm
    - name: Install `rust-src` Rustup Component
      run: rustup component add rust-src llvm-tools-preview
    - name: Run build
      run: cargo boot build
    - name: Build Docs
      run: cd src/ && cargo doc
    - name: Create index.html redirect
      run: pwd && cd src/ && echo "<meta http-equiv='refresh' content='0; URL=https://andy-python-programmer.github.io/aero/aero/index.html' />" > ./target/x86_64-aero_os/doc/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/target/x86_64-aero_os/doc
