name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install dependencies
      run: sudo apt-get install -y nasm meson ninja-build
    - name: Run build
      run: cargo aero build --release
    - name: Build Docs
      run: cargo aero web
    - name: Uploading image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Aero
        path: ./build/aero.img
    
  deploy_docs:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'schedule')

    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/build/

  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install dependencies
      run: sudo apt-get install -y nasm meson ninja-build
    - name: Install QEMU x86_64
      run: sudo apt update && sudo apt install qemu-system-x86
    - name: Qemu Version
      run: qemu-system-x86_64 --version
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo aero test --features=ci --bios uefi -- -display none -device isa-debug-exit,iobase=0xf4,iosize=0x04