name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install dependencies
      run: sudo apt-get install -y nasm meson ninja-build
    - name: Run build
      run: cargo aero build --release
    - name: Build Docs
      run: cargo aero web
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/build/
    - name: Uploading image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Aero
        path: ./build/aero.img
