name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - uses: actions-rs/components-nightly@v1
      with:
        toolchain: nightly
        component: rust-src
    - name: Install bootimage
      run: cargo install bootimage
    - name: Run build
      run: cargo bootimage